version: "3.8"

services:
  mysql-db:
    image: mysql:8
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: eventbox
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql  

  mongo-db:
    image: mongo:6
    container_name: mongo-db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db  

  auth-service:
    build: ./backend/AuthenService
    container_name: auth-service
    restart: always
    depends_on:
      - mongo-db
    ports:
      - "8081:8081"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo-db:27017/auth_db

  blog-service:
    build: ./backend/BlogService
    container_name: blog-service
    restart: always
    depends_on:
      - mongo-db
    ports:
      - "8083:8083"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo-db:27017/blog_db

  event-service:
    build: ./backend/EventService  
    container_name: event-service
    restart: always
    depends_on:
      - mysql-db
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/eventbox
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: "root"

  gateway:
    build: ./backend/gateway
    container_name: gateway
    restart: always
    depends_on:
      - auth-service
      - blog-service
      - event-service
    ports:
      - "8080:8080"
      
  frontend-user:
    build: 
      context: ./frontend/user
      dockerfile: Dockerfile
    container_name: frontend-user
    restart: always
    depends_on:
      - gateway
    ports:
      - "3001:80"


  frontend-admin:
    build: 
      context: ./frontend/company
      dockerfile: Dockerfile
    container_name: frontend-company
    restart: always
    depends_on:
      - gateway
    ports:
      - "3002:80"



volumes:
  mysql-data:
  mongo-data:
