version: "3.8"

services:
  mongodb:
    image: mongo:5
    container_name: mongo-db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  blog-service:
    build: .
    container_name: blog-service
    restart: always
    depends_on:
      - mongodb
    ports:
      - "8083:8083"
    environment:
      SERVER_PORT: 8083
      SPRING_DATA_MONGODB_HOST: mongodb
      SPRING_DATA_MONGODB_PORT: 27017
      SPRING_DATA_MONGODB_DATABASE: blog_db

      MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: health,info

volumes:
  mongo-data:
